<?php $menu = $this->getMenu() ?>
<?php $baseUrl = $block->getBaseUrl(); ?>
<div class="block account-nav panel panel-default">
	<div class="panel-body">
		<nav class="account-nav">
			<ul class="nav linkitems">
				<?php if ($this->getRequest()->getParam('id') == "") : ?>
					<li class="nav linkthatitem "><strong>All</strong></li>
				<?php else : ?>
					<li class="nav linkthatitem current"><a class="linkitem" href="<?= $baseUrl . "portfolio" ?>">All</a></li>
				<?php endif ?>
				<?php foreach ($menu as $_menu) : ?>
					<?php if ($_menu->getCategoryName() == 'Hidden' || $_menu->getCategoryName() == 'All') : 
						continue;
						?>
					<?php else : ?>
						<?php if ($_menu->getId() == $this->getRequest()->getParam('id')) : ?>
							<li class="nav linkthatitem "><strong><?php echo $_menu->getCategoryName() ?></strong></li>
						<?php else : ?>
							<li class="nav linkthatitem"><a class="linkitem" href="<?php echo $_menu->getLinkCate(); ?>"><?php echo $_menu->getCategoryName() ?></a></li>
						<?php endif ?>
					<?php endif ?>
				<?php endforeach; ?>
			</ul>
		</nav>
	</div>
</div>