<?php $portfolios = $this->getPortfolios()
?>
<div class="portfolio-container">
	<?php if ($this->getTitle()) : ?>
		<div class="block-title">
			<h3><?php echo $this->getTitle() ?></h3>
		</div>
	<?php endif ?>
	<?php if ($this->hasData('note_text')) : ?>
		<div class="note-text">
			<span><?php echo $this->getData('note_text') ?></span>
		</div>
	<?php endif ?>
	<?php if (count($portfolios) > 0) : ?>
		<?php
		$helper = $this->helper('Risecommerce\Portfolio\Helper\Data');
		$col = '';
		if ($this->hasData('per_row')) {
			$col = $this->getData('per_row');
			$col = $helper->getColClass($col);
		}
		?>

		<div class="portfolio-grid">
		<?php foreach ($portfolios as $portfolio) : ?>
			<div class="col-md-4 col-sm-4 col-xs-12">
				<button id="button">
					<div class="portfolio-top-content">
						<?php $thumbnailUrl = $this->getThumbnailSrc($portfolio) ?>
						<?php $portfolioUrl = $this->getPortfolioAddress($portfolio) ?>
						<?php if ($thumbnailUrl) : ?>
							<!-- <img src="<?php// echo $thumbnailUrl ?>" alt="" class="img-responsive" /> -->
						<?php endif ?>
						<span class="hover-info">
							<span class="fa fa-search"></span>
							<span class="project"><?php echo $portfolio->getServices() ?></span>
							<span class="categories"><?php echo $this->getCategoriesText($portfolio) ?></span>
						</span>
					</div>
				</button>


				<div id="modal">
					<div class="modal-body-content">
						<?php if ($thumbnailUrl) : ?>
							<img src="<?php echo $thumbnailUrl ?>" alt="" class="img-responsive" />
						<?php endif ?>
						<p><?= $block->escapeHtml(__('Content')) ?></p>
					</div>
				</div>

				<div class="portfolio-bottom-content">
					<h4><?php echo $portfolio->getName() ?></h4>
				</div>
			</div>
		<?php endforeach ?>

		</div>

	<?php else : ?>
		<p class="note-msg"><?php echo $this->__('There are no portfolios matching the selection.') ?></p>
	<?php endif ?>
</div>
